config/routes.rb
Tasks::Application.routes.draw do
  root :to => 'Tasks#index'
  get "tasks/index"

    resources :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :task
  
  validates :task, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @task = Task.new
    @tasks = Task.all
  end
  
  def create
    #render :text => params.inspect
    Task.create params[:task]
    redirect_to :back
  end
  
  def edit
    @task = Task.find params[:id]
  end
  
  def update
    task = Task.find params[:id]
    
    if task.update_attributes params[:task]
      redirect_to tasks_path, :notice => 'Your task has been successfully updated'
    else
      redirect_to :back, :notice => 'There was an error updating your task.'
    end
  end
  
  def destroy
    Task.destroy params[:id]
    redirect_to :back, :notice => 'Task has been deleted.'
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, message| %>
  <%= content_tag :div, message, :id => "flash_#{name}" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
  <%= f.label :task %>
  <%= f.text_field :task %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<%= render 'form' %>

<ul>
  <% for task in @tasks %>
  <li id="task_<%= task.id %>">
    <%= task.task %>
    <%= link_to 'Edit', edit_task_path(task) %>
    <%= link_to 'Delete', task, :method => 'delete' %>
  </li>
  <% end %>
</ul>